all:Node.cpp Stack.cpp main_stack.cpp Tnode.cpp Btree.cpp main_tree.cpp
	g++ Node.cpp Stack.cpp main_stack.cpp -o HW3A_stack
	g++ Tnode.cpp Btree.cpp main_tree.cpp -o HW3A_tree
clean:
	rm -f HW3A_stack 
	rm -f HW3A_tree

